### ISSUE TITLE
use with VPN?

### ISSUE THREAD

**Issue by dataSQL** [TechnitiumSoftware/TechnitiumLibrary#1]
Hello Shreyas Zare,

Love your TMAC.  

I use internet cafes and is it possible to change the MAC address on such temporary use computers without ADMIN access?

On my personal machine, laptop, when I use a VPN, it creates a new driver that directly references the original MAC.  How can I maintain TMAC control in forcing the use of the created MAC address?

**Comment by ShreyasZare** [comment]
Please dont write emails in github issue tracker. You should send email to support@technitium.com for any queries.

You cannot change MAC address without admin rights. You dont really need to change MAC address to hide it from internet websites since your MAC address is visible only in the local LAN network and it cannot be seen beyond your router. 

For VPN networks, the network adapters that get installed are just software emulated devices and are not real network adapter to have a need for MAC address. You dont need to think about MAC address when using VPN.
