### ISSUE TITLE
Refactor code to make it easier to understand

### ISSUE THREAD

**Issue by PonchoPowers** [TechnitiumSoftware/TechnitiumLibrary#2]
Code such as:

`if ((labelLength & 0xC0) == 0xC0)`

Should be refactored to make it easier to understand.

What exactly is this code supposed to be doing?

**Comment by Matthew-Bonner** [comment]
My point is mainly this, if you define constants for these codes, people will understand the code better.

Take a look at the following for example:
https://github.com/isc-projects/bind9/blob/fa03f941027cdcccc060613f773e63701b5baa77/doc/design/dscp

```#define ISC_NET_DSCPRECVV4      0x01    /* Can receive sent DSCP value IPv4 */
#define ISC_NET_DSCPRECVV6      0x02    /* Can receive sent DSCP value IPv6 */
#define ISC_NET_DSCPSETV4       0x04    /* Can set DSCP on socket IPv4 */
#define ISC_NET_DSCPSETV6       0x08    /* Can set DSCP on socket IPv6 */
#define ISC_NET_DSCPPKTV4       0x10    /* Can set DSCP on per packet IPv4 */
#define ISC_NET_DSCPPKTV6       0x20    /* Can set DSCP on per packet IPv6 */
#define ISC_NET_DSCPALL         0x3f    /* All valid flags */
```

By using `ISC_NET_DSCPALL` rather than `0x3f` is much more insightful. And then if needed, you can even comment on what `0x3f` is referring to.

**Comment by ShreyasZare** [comment]
Fair point.
